name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: Run tests
    uses: ./.github/workflows/tests.yml
  check-semver:
    name: Check crate semver
    needs: [tests]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
  publish:
    name: Publish crate
    if: github.repository == 'kylewlacy/tick-encoding'
    needs: [tests, check-semver]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
